import type {
  CommunityPost,
  DiscussionThread,
  Listing,
  LiteracyEntry,
  Product,
  SeedAuthor,
  YoutubeComment,
} from './types';

export const authors: Record<string, SeedAuthor> = {
  amara: {
    id: 'user-amara',
    displayName: 'Amara O.',
    skinType: 'oily',
    memberSince: '2026-03-01',
    verified: true,
    knownFor: [
      { tag: 'Oily skin', answers: 14 },
      { tag: 'Acne-prone', answers: 6 },
    ],
  },
  ken: {
    id: 'user-ken',
    displayName: 'Ken I.',
    skinType: 'combination',
    memberSince: '2026-01-12',
    verified: true,
    knownFor: [{ tag: 'Combination', answers: 8 }],
  },
  zainab: {
    id: 'user-zainab',
    displayName: 'Zainab M.',
    skinType: 'sensitive',
    memberSince: '2026-04-18',
    verified: false,
    knownFor: [],
  },
  tola: {
    id: 'user-tola',
    displayName: 'Tola A.',
    skinType: 'combination',
    memberSince: '2025-11-02',
    verified: true,
    knownFor: [{ tag: 'Combination', answers: 5 }],
  },
};

export const products: Product[] = [
  {
    id: 'niacinamide-10-zinc',
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    description:
      'A lightweight serum with 10% niacinamide and 1% zinc PCA. Often used for visible pores and excess oil. Results, if any, are typically discussed after several weeks of consistent use.',
    category: 'serum',
    ingredients: ['niacinamide', 'zinc_pca', 'glycerin', 'pentylene_glycol'],
    attributeTags: ['fragrance_free', 'oil_free', 'mattifying'],
    suitsSkinTypes: ['oily', 'combination'],
    heroEmoji: '🧴',
    typicalDurationDays: 70,
    shelfLifeMonths: 12,
    source: 'seed',
  },
  {
    id: 'gentle-foaming-cleanser',
    name: 'Gentle Foaming Cleanser',
    brand: 'CeraVe',
    description:
      'A foaming cleanser with ceramides and niacinamide. Designed to remove oil and sunscreen without a tight after-feel for many people.',
    category: 'cleanser',
    ingredients: ['ceramides', 'niacinamide', 'hyaluronic_acid', 'glycerin'],
    attributeTags: ['fragrance_free', 'gentle', 'barrier_repair'],
    suitsSkinTypes: ['oily', 'combination', 'normal', 'sensitive'],
    heroEmoji: '🧼',
    typicalDurationDays: 90,
    shelfLifeMonths: 12,
    source: 'seed',
  },
  {
    id: 'barrier-repair-moisturizer',
    name: 'Barrier Repair Moisturizer',
    brand: 'CeraVe',
    description:
      'A ceramide moisturizer meant to support the skin barrier. Texture is richer than a gel cream.',
    category: 'moisturizer',
    ingredients: ['ceramides', 'cholesterol', 'hyaluronic_acid', 'petrolatum'],
    attributeTags: ['barrier_repair', 'hydrating', 'fragrance_free'],
    suitsSkinTypes: ['dry', 'combination', 'sensitive', 'normal'],
    heroEmoji: '🧪',
    typicalDurationDays: 60,
    shelfLifeMonths: 12,
    source: 'seed',
  },
  {
    id: 'clarifying-niacinamide-gel',
    name: 'Clarifying Niacinamide Gel',
    brand: 'SkinLab',
    description:
      'A water-gel niacinamide treatment with a mattifying finish. Some users with dry cheeks find it too stripping.',
    category: 'treatment',
    ingredients: ['niacinamide', 'zinc_pca', 'silica'],
    attributeTags: ['mattifying', 'oil_free'],
    suitsSkinTypes: ['oily'],
    heroEmoji: '🧴',
    typicalDurationDays: 55,
    shelfLifeMonths: 12,
    source: 'seed',
  },
  {
    id: 'balance-serum-5',
    name: 'Balance Serum 5%',
    brand: 'Pure Beauty Co',
    description:
      'A 5% niacinamide serum in an oil-free base. Lower strength than 10% formulas.',
    category: 'serum',
    ingredients: ['niacinamide', 'glycerin', 'panthenol'],
    attributeTags: ['oil_free', 'fragrance_free', 'gentle'],
    suitsSkinTypes: ['oily', 'combination', 'sensitive', 'normal'],
    heroEmoji: '🧪',
    typicalDurationDays: 75,
    shelfLifeMonths: 12,
    source: 'seed',
  },
  {
    id: 'pore-minimizing-essence',
    name: 'Pore Minimizing Essence',
    brand: 'The Serum Room',
    description:
      'A watery essence marketed around the look of pores. Ingredient list is shorter than most serums in this catalog.',
    category: 'essence',
    ingredients: ['niacinamide', 'hamamelis'],
    attributeTags: ['mattifying'],
    suitsSkinTypes: ['oily', 'combination'],
    heroEmoji: '🫙',
    typicalDurationDays: 45,
    shelfLifeMonths: 10,
    source: 'seed',
  },
  {
    id: 'vitamin-c-15',
    name: 'Vitamin C Serum 15%',
    brand: 'Glow Depot',
    description:
      'An ascorbic acid serum. Unstable if left open and warm; patch-test, especially on sensitive skin.',
    category: 'serum',
    ingredients: ['ascorbic_acid', 'ferulic_acid', 'vitamin_e', 'glycerin'],
    attributeTags: ['antioxidant', 'vitamin_c'],
    suitsSkinTypes: ['normal', 'dry', 'combination'],
    heroEmoji: '🧪',
    typicalDurationDays: 50,
    shelfLifeMonths: 6,
    source: 'seed',
  },
  {
    id: 'clay-mask',
    name: 'Clay Mask',
    brand: 'SkinLab',
    description:
      'A kaolin clay mask for occasional use. Can feel tight if left on until fully dry.',
    category: 'mask',
    ingredients: ['kaolin', 'bentonite', 'glycerin'],
    attributeTags: ['mattifying'],
    suitsSkinTypes: ['oily', 'combination'],
    heroEmoji: '🫙',
    typicalDurationDays: 120,
    shelfLifeMonths: 24,
    source: 'seed',
  },
  {
    id: 'mineral-spf-50',
    name: 'Mineral SPF 50',
    brand: 'Pure Beauty Co',
    description:
      'A zinc oxide sunscreen. Leaves a slight white cast on deeper skin tones for some people.',
    category: 'spf',
    ingredients: ['zinc_oxide', 'titanium_dioxide', 'glycerin'],
    attributeTags: ['fragrance_free', 'gentle'],
    suitsSkinTypes: ['sensitive', 'dry', 'normal', 'combination', 'oily'],
    heroEmoji: '☀️',
    typicalDurationDays: 40,
    shelfLifeMonths: 12,
    source: 'seed',
  },
  {
    id: 'salicylic-cleanser',
    name: 'Salicylic Cleanser',
    brand: 'SkinLab',
    description:
      'A 2% salicylic acid cleanser for occasional use on oily or congestion-prone skin. Can over-dry if used twice daily.',
    category: 'cleanser',
    ingredients: ['salicylic_acid', 'glycerin'],
    attributeTags: ['mattifying', 'oil_free'],
    suitsSkinTypes: ['oily', 'combination'],
    heroEmoji: '🧼',
    typicalDurationDays: 80,
    shelfLifeMonths: 12,
    source: 'seed',
  },
  {
    id: 'barrier-repair-cream',
    name: 'Barrier Repair Cream',
    brand: 'CeraVe',
    description:
      'A richer cream for dry or weather-stressed skin. Can feel heavy in humid weather.',
    category: 'moisturizer',
    ingredients: ['ceramides', 'shea_butter', 'glycerin', 'cholesterol'],
    attributeTags: ['hydrating', 'barrier_repair', 'fragrance_free'],
    suitsSkinTypes: ['dry', 'sensitive', 'normal'],
    heroEmoji: '🧴',
    typicalDurationDays: 50,
    shelfLifeMonths: 12,
    source: 'seed',
  },
];

export const listings: Listing[] = [
  {
    id: 'list-1',
    productId: 'niacinamide-10-zinc',
    merchantName: 'Glow Depot NG',
    price: 8400,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/glow-depot/niacinamide',
    shipsNote: 'Ships in 2–3 days',
    optedOut: false,
  },
  {
    id: 'list-2',
    productId: 'niacinamide-10-zinc',
    merchantName: 'SkinLab Store',
    price: 8950,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/skinlab/niacinamide',
    shipsNote: 'Ships in 1–2 days',
    optedOut: false,
  },
  {
    id: 'list-3',
    productId: 'niacinamide-10-zinc',
    merchantName: 'Pure Beauty Co',
    price: 9200,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/pure-beauty/niacinamide',
    shipsNote: 'Ships in 4–6 days',
    optedOut: false,
  },
  {
    id: 'list-4',
    productId: 'niacinamide-10-zinc',
    merchantName: 'The Serum Room',
    price: 8700,
    currency: 'NGN',
    inStock: false,
    productUrl: 'https://example.com/serum-room/niacinamide',
    shipsNote: 'Out of stock',
    optedOut: false,
  },
  {
    id: 'list-5',
    productId: 'niacinamide-10-zinc',
    merchantName: 'Bloom Skin NG',
    price: 9100,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/bloom/niacinamide',
    shipsNote: 'Ships in 3–5 days',
    optedOut: false,
  },
  {
    id: 'list-6',
    productId: 'niacinamide-10-zinc',
    merchantName: 'Derma Shelf',
    price: 8600,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/derma/niacinamide',
    shipsNote: 'Ships in 2–4 days',
    optedOut: false,
  },
  {
    id: 'list-7',
    productId: 'gentle-foaming-cleanser',
    merchantName: 'Glow Depot NG',
    price: 12500,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/glow-depot/cleanser',
    shipsNote: 'Ships in 2–3 days',
    optedOut: false,
  },
  {
    id: 'list-8',
    productId: 'gentle-foaming-cleanser',
    merchantName: 'SkinLab Store',
    price: 13200,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/skinlab/cleanser',
    shipsNote: 'Ships in 1–2 days',
    optedOut: false,
  },
  {
    id: 'list-9',
    productId: 'barrier-repair-moisturizer',
    merchantName: 'Pure Beauty Co',
    price: 14800,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/pure-beauty/moisturizer',
    shipsNote: 'Ships in 4–6 days',
    optedOut: false,
  },
  {
    id: 'list-10',
    productId: 'barrier-repair-cream',
    merchantName: 'Glow Depot NG',
    price: 11200,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/glow-depot/cream',
    shipsNote: 'Ships in 2–3 days',
    optedOut: false,
  },
  {
    id: 'list-11',
    productId: 'barrier-repair-cream',
    merchantName: 'SkinLab Store',
    price: 12100,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/skinlab/cream',
    shipsNote: 'Ships in 1–2 days',
    optedOut: false,
  },
  {
    id: 'list-12',
    productId: 'vitamin-c-15',
    merchantName: 'Glow Depot NG',
    price: 14500,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/glow-depot/vitc',
    shipsNote: 'Ships in 2–3 days',
    optedOut: false,
  },
  {
    id: 'list-13',
    productId: 'vitamin-c-15',
    merchantName: 'Pure Beauty Co',
    price: 15200,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/pure-beauty/vitc',
    shipsNote: 'Ships in 4–6 days',
    optedOut: false,
  },
  {
    id: 'list-14',
    productId: 'vitamin-c-15',
    merchantName: 'The Serum Room',
    price: 14900,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/serum-room/vitc',
    shipsNote: 'Ships in 3–4 days',
    optedOut: false,
  },
  {
    id: 'list-15',
    productId: 'vitamin-c-15',
    merchantName: 'Derma Shelf',
    price: 15500,
    currency: 'NGN',
    inStock: false,
    productUrl: 'https://example.com/derma/vitc',
    shipsNote: 'Out of stock',
    optedOut: false,
  },
  {
    id: 'list-16',
    productId: 'clay-mask',
    merchantName: 'SkinLab Store',
    price: 6800,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/skinlab/mask',
    shipsNote: 'Ships in 1–2 days',
    optedOut: false,
  },
  {
    id: 'list-17',
    productId: 'clay-mask',
    merchantName: 'Glow Depot NG',
    price: 7200,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/glow-depot/mask',
    shipsNote: 'Ships in 2–3 days',
    optedOut: false,
  },
  {
    id: 'list-18',
    productId: 'mineral-spf-50',
    merchantName: 'Pure Beauty Co',
    price: 12000,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/pure-beauty/spf',
    shipsNote: 'Ships in 4–6 days',
    optedOut: false,
  },
  {
    id: 'list-19',
    productId: 'mineral-spf-50',
    merchantName: 'Glow Depot NG',
    price: 12400,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/glow-depot/spf',
    shipsNote: 'Ships in 2–3 days',
    optedOut: false,
  },
  {
    id: 'list-20',
    productId: 'mineral-spf-50',
    merchantName: 'SkinLab Store',
    price: 12800,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/skinlab/spf',
    shipsNote: 'Ships in 1–2 days',
    optedOut: false,
  },
  {
    id: 'list-21',
    productId: 'mineral-spf-50',
    merchantName: 'Derma Shelf',
    price: 11900,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/derma/spf',
    shipsNote: 'Ships in 2–4 days',
    optedOut: false,
  },
  {
    id: 'list-22',
    productId: 'mineral-spf-50',
    merchantName: 'Bloom Skin NG',
    price: 13000,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/bloom/spf',
    shipsNote: 'Ships in 3–5 days',
    optedOut: false,
  },
  {
    id: 'list-23',
    productId: 'clarifying-niacinamide-gel',
    merchantName: 'SkinLab Store',
    price: 7800,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/skinlab/gel',
    shipsNote: 'Ships in 1–2 days',
    optedOut: false,
  },
  {
    id: 'list-24',
    productId: 'balance-serum-5',
    merchantName: 'Pure Beauty Co',
    price: 6500,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/pure-beauty/balance',
    shipsNote: 'Ships in 4–6 days',
    optedOut: false,
  },
  {
    id: 'list-26',
    productId: 'salicylic-cleanser',
    merchantName: 'SkinLab Store',
    price: 8900,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/skinlab/salicylic',
    shipsNote: 'Ships in 1–2 days',
    optedOut: false,
  },
  {
    id: 'list-25',
    productId: 'pore-minimizing-essence',
    merchantName: 'The Serum Room',
    price: 5400,
    currency: 'NGN',
    inStock: true,
    productUrl: 'https://example.com/serum-room/essence',
    shipsNote: 'Ships in 3–4 days',
    optedOut: false,
  },
];

export const literacyEntries: LiteracyEntry[] = [
  {
    attributeTag: 'niacinamide',
    title: 'Niacinamide',
    body: 'Niacinamide is a form of vitamin B3 used in many leave-on products. People often look at it for the look of pores and excess oil. Visible change, if it happens, is commonly discussed after 4–8 weeks — not overnight. It is not a medical treatment.',
    sourceNote: 'General ingredient literacy, not medical advice',
  },
  {
    attributeTag: 'zinc_pca',
    title: 'Zinc PCA',
    body: 'Zinc PCA is a zinc salt used in some oil-control formulas. A few people with sensitive skin notice dryness or tightness. Patch-test before using on the whole face.',
    sourceNote: 'General ingredient literacy, not medical advice',
  },
  {
    attributeTag: 'ceramides',
    title: 'Ceramides',
    body: 'Ceramides are lipids already present in skin. In moisturizers they are used to support the look and feel of the barrier, especially after cleansing.',
    sourceNote: 'General ingredient literacy, not medical advice',
  },
  {
    attributeTag: 'ascorbic_acid',
    title: 'Ascorbic acid (vitamin C)',
    body: 'L-ascorbic acid is an antioxidant that oxidizes when exposed to air and light. Color change toward brown usually means the formula has degraded. Patch-test; stinging is commonly reported on compromised skin.',
    sourceNote: 'General ingredient literacy, not medical advice',
  },
  {
    attributeTag: 'zinc_oxide',
    title: 'Zinc oxide',
    body: 'Zinc oxide is a mineral UV filter. It sits on the skin rather than absorbing in. A white cast can show on deeper skin tones depending on the formula.',
    sourceNote: 'General ingredient literacy, not medical advice',
  },
  {
    attributeTag: 'fragrance_free',
    title: 'Fragrance-free',
    body: 'Fragrance-free means no added perfume. It does not guarantee the formula is non-irritating. Essential oils and some plant extracts can still bother reactive skin.',
    sourceNote: 'General ingredient literacy, not medical advice',
  },
];

function post(
  partial: Omit<CommunityPost, 'status' | 'parentPostId'> & {
    parentPostId?: string | null;
    threadId?: string | null;
    photoUrl?: string | null;
  },
): CommunityPost {
  return {
    status: 'visible',
    parentPostId: partial.parentPostId ?? null,
    threadId: partial.threadId ?? null,
    photoUrl: partial.photoUrl ?? null,
    ...partial,
  };
}

export const discussionThreads: DiscussionThread[] = [
  {
    id: 'thread-oily',
    productId: 'niacinamide-10-zinc',
    title: 'Alternatives for oily skin?',
    createdBy: authors.zainab.id,
    createdAt: '2026-09-10T09:00:00.000Z',
  },
  {
    id: 'thread-results',
    productId: 'niacinamide-10-zinc',
    title: '3 weeks in — results',
    createdBy: authors.amara.id,
    createdAt: '2026-07-18T10:00:00.000Z',
  },
  {
    id: 'thread-makeup',
    productId: 'niacinamide-10-zinc',
    title: 'Does this work under makeup?',
    createdBy: authors.tola.id,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'thread-cleanser-gentle',
    productId: 'gentle-foaming-cleanser',
    title: 'Does this strip combination skin?',
    createdBy: authors.ken.id,
    createdAt: '2026-08-10T11:00:00.000Z',
  },
  {
    id: 'thread-barrier-spf',
    productId: 'barrier-repair-moisturizer',
    title: 'Is this too occlusive under mineral SPF?',
    createdBy: authors.zainab.id,
    createdAt: '2026-09-12T11:00:00.000Z',
  },
  {
    id: 'thread-salicylic-purge',
    productId: 'salicylic-cleanser',
    title: 'Purging vs a real breakout',
    createdBy: authors.amara.id,
    createdAt: '2026-04-02T11:00:00.000Z',
  },
  {
    id: 'thread-gel-dry',
    productId: 'clarifying-niacinamide-gel',
    title: 'Too drying for combination cheeks?',
    createdBy: authors.tola.id,
    createdAt: '2026-08-01T11:00:00.000Z',
  },
];

export const communityPosts: CommunityPost[] = [
  post({
    id: 'post-1',
    productId: 'niacinamide-10-zinc',
    userId: authors.amara.id,
    authorName: authors.amara.displayName,
    threadId: 'thread-results',
    type: 'experience',
    body: 'Cut my midday shine noticeably by week 5. One thing nobody mentions: layer it under sunscreen or it pills badly.',
    traitTags: ['Oily', '6mo in'],
    isVerifiedOwner: true,
    helpfulCount: 34,
    createdAt: '2026-08-02T10:00:00.000Z',
  }),
  post({
    id: 'post-2',
    productId: 'niacinamide-10-zinc',
    userId: authors.zainab.id,
    authorName: authors.zainab.displayName,
    threadId: 'thread-oily',
    type: 'question',
    body: 'Anyone with sensitive + oily skin used this? Worried about the zinc.',
    traitTags: ['Sensitive', 'Oily'],
    isVerifiedOwner: false,
    helpfulCount: 2,
    createdAt: '2026-09-13T09:00:00.000Z',
  }),
  post({
    id: 'post-3',
    productId: 'niacinamide-10-zinc',
    userId: authors.ken.id,
    authorName: authors.ken.displayName,
    threadId: 'thread-results',
    type: 'experience',
    body: 'Honestly saw nothing for the first month. Month two it started working.',
    traitTags: ['Combo', '2mo in'],
    isVerifiedOwner: true,
    helpfulCount: 12,
    createdAt: '2026-07-20T12:00:00.000Z',
  }),
  post({
    id: 'post-4',
    productId: 'niacinamide-10-zinc',
    userId: authors.tola.id,
    authorName: authors.tola.displayName,
    threadId: 'thread-makeup',
    type: 'update',
    body: 'Third month in — still no breakouts, but it does pill under sunscreen.',
    traitTags: ['Oily', '3mo'],
    isVerifiedOwner: true,
    helpfulCount: 9,
    createdAt: '2026-09-10T08:00:00.000Z',
  }),
  post({
    id: 'post-5',
    productId: 'gentle-foaming-cleanser',
    userId: authors.ken.id,
    authorName: authors.ken.displayName,
    threadId: 'thread-cleanser-gentle',
    type: 'experience',
    body: 'Took about 3 weeks before I noticed any real difference. Does not strip my cheeks the way gel cleansers did.',
    traitTags: ['Combo'],
    isVerifiedOwner: true,
    helpfulCount: 18,
    createdAt: '2026-08-21T11:00:00.000Z',
  }),
  post({
    id: 'post-6',
    productId: 'gentle-foaming-cleanser',
    userId: authors.amara.id,
    authorName: authors.amara.displayName,
    threadId: 'thread-cleanser-gentle',
    type: 'experience',
    body: 'Removes SPF without leaving that squeaky film. I use it AM and PM.',
    traitTags: ['Oily', '4mo in'],
    isVerifiedOwner: true,
    helpfulCount: 11,
    createdAt: '2026-06-14T11:00:00.000Z',
  }),
  post({
    id: 'post-7',
    productId: 'clarifying-niacinamide-gel',
    userId: authors.tola.id,
    authorName: authors.tola.displayName,
    threadId: 'thread-gel-dry',
    type: 'experience',
    body: 'Mattifies well on my T-zone. Cheeks felt tight by week two so I moved it to spot use only.',
    traitTags: ['Combo', '2mo in'],
    isVerifiedOwner: true,
    helpfulCount: 7,
    createdAt: '2026-08-01T11:00:00.000Z',
  }),
  post({
    id: 'post-8',
    productId: 'clarifying-niacinamide-gel',
    userId: authors.amara.id,
    authorName: authors.amara.displayName,
    threadId: 'thread-gel-dry',
    type: 'experience',
    body: 'Works for my oily skin. I would not give it to a friend with dry cheeks.',
    traitTags: ['Oily', '1mo in'],
    isVerifiedOwner: true,
    helpfulCount: 4,
    createdAt: '2026-09-01T11:00:00.000Z',
  }),
  post({
    id: 'post-9',
    productId: 'barrier-repair-moisturizer',
    userId: authors.ken.id,
    authorName: authors.ken.displayName,
    threadId: 'thread-barrier-spf',
    type: 'experience',
    body: 'Helped my cheeks. Feels heavy on my forehead in Lagos humidity.',
    traitTags: ['Combo', '6mo in'],
    isVerifiedOwner: true,
    helpfulCount: 8,
    createdAt: '2026-05-02T11:00:00.000Z',
  }),
  post({
    id: 'post-10',
    productId: 'barrier-repair-moisturizer',
    userId: authors.zainab.id,
    authorName: authors.zainab.displayName,
    threadId: 'thread-barrier-spf',
    type: 'question',
    body: 'Is this too occlusive under mineral SPF?',
    traitTags: ['Sensitive'],
    isVerifiedOwner: false,
    helpfulCount: 1,
    createdAt: '2026-09-12T11:00:00.000Z',
  }),
  post({
    id: 'post-11',
    productId: 'salicylic-cleanser',
    userId: authors.amara.id,
    authorName: authors.amara.displayName,
    threadId: 'thread-salicylic-purge',
    type: 'experience',
    body: 'Gave me a mild purge for 2 weeks, then settled.',
    traitTags: ['Oily'],
    isVerifiedOwner: true,
    helpfulCount: 18,
    createdAt: '2026-04-02T11:00:00.000Z',
  }),
  post({
    id: 'feed-1',
    productId: 'niacinamide-10-zinc',
    userId: authors.amara.id,
    authorName: authors.amara.displayName,
    type: 'feed_post',
    body: '3 weeks in — texture is so much smoother',
    photoUrl: 'tile:smooth',
    traitTags: ['Oily'],
    isVerifiedOwner: true,
    helpfulCount: 22,
    createdAt: '2026-08-20T10:00:00.000Z',
  }),
  post({
    id: 'feed-2',
    productId: 'niacinamide-10-zinc',
    userId: authors.ken.id,
    authorName: authors.ken.displayName,
    type: 'feed_post',
    body: 'Morning shelf — what I pair this with',
    photoUrl: 'tile:shelf',
    traitTags: ['Combo'],
    isVerifiedOwner: true,
    helpfulCount: 9,
    createdAt: '2026-08-28T08:00:00.000Z',
  }),
  post({
    id: 'feed-3',
    productId: 'clarifying-niacinamide-gel',
    userId: authors.tola.id,
    authorName: authors.tola.displayName,
    type: 'feed_post',
    body: 'Honestly regret this one — broke me out on my cheeks',
    photoUrl: 'tile:regret',
    traitTags: ['Combo'],
    isVerifiedOwner: true,
    helpfulCount: 15,
    createdAt: '2026-08-12T12:00:00.000Z',
  }),
  post({
    id: 'feed-4',
    productId: 'gentle-foaming-cleanser',
    userId: authors.zainab.id,
    authorName: authors.zainab.displayName,
    type: 'feed_post',
    body: 'Layering order that finally worked',
    photoUrl: 'tile:layer',
    traitTags: ['Sensitive'],
    isVerifiedOwner: false,
    helpfulCount: 6,
    createdAt: '2026-09-02T09:00:00.000Z',
  }),
  post({
    id: 'feed-5',
    productId: 'barrier-repair-moisturizer',
    userId: authors.ken.id,
    authorName: authors.ken.displayName,
    type: 'feed_post',
    body: 'Humidity test: this sits heavy on my T-zone',
    photoUrl: 'tile:humid',
    traitTags: ['Combo'],
    isVerifiedOwner: true,
    helpfulCount: 5,
    createdAt: '2026-05-10T11:00:00.000Z',
  }),
  post({
    id: 'feed-6',
    productId: 'salicylic-cleanser',
    userId: authors.amara.id,
    authorName: authors.amara.displayName,
    type: 'feed_post',
    body: 'Week 2 purge was real. Week 4 my jawline calmed down.',
    photoUrl: 'tile:purge',
    traitTags: ['Oily'],
    isVerifiedOwner: true,
    helpfulCount: 19,
    createdAt: '2026-04-16T11:00:00.000Z',
  }),
];

export const youtubeComments: YoutubeComment[] = [
  {
    id: 'ytc-1',
    productId: 'niacinamide-10-zinc',
    youtubeVideoId: 'bootstrap',
    authorDisplayName: 'SkinNotes',
    body: 'I used this for 8 weeks on oily skin. Pores looked smaller but it pilled under every sunscreen I own.',
    fetchedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'ytc-2',
    productId: 'niacinamide-10-zinc',
    youtubeVideoId: 'bootstrap',
    authorDisplayName: 'RoutineDump',
    body: 'If you are dry, skip this. My cheeks felt tight by day four.',
    fetchedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'ytc-3',
    productId: 'gentle-foaming-cleanser',
    youtubeVideoId: 'bootstrap',
    authorDisplayName: 'LagosSkincare',
    body: 'Takes off mineral SPF without that squeak. I still double cleanse at night.',
    fetchedAt: '2026-09-01T00:00:00.000Z',
  },
];

export const KEYWORD_ALIASES: Record<string, string[]> = {
  mattifying: ['mattifying', 'matte', 'oil control', 'shine'],
  hydrating: ['hydrating', 'dewy', 'moisturizing', 'dry'],
  fragrance_free: ['fragrance-free', 'fragrance free', 'unscented', 'no perfume'],
  oil_free: ['oil-free', 'oil free', 'non greasy', 'non-greasy'],
  niacinamide: ['niacinamide', 'b3', 'vitamin b3'],
  barrier_repair: ['barrier', 'ceramides', 'repair'],
  gentle: ['gentle', 'sensitive', 'calming'],
  vitamin_c: ['vitamin c', 'ascorbic', 'brightening'],
};

export const BROWSE_CHIPS = [
  { id: 'oily', label: 'Oily skin', kind: 'skin' as const, value: 'oily' },
  { id: 'mattifying', label: 'Mattifying', kind: 'tag' as const, value: 'mattifying' },
  { id: 'oil_free', label: 'Oil-free', kind: 'tag' as const, value: 'oil_free' },
  { id: 'fragrance_free', label: 'Fragrance-free', kind: 'tag' as const, value: 'fragrance_free' },
  { id: 'combination', label: 'Combination', kind: 'skin' as const, value: 'combination' },
  { id: 'sensitive', label: 'Sensitive', kind: 'skin' as const, value: 'sensitive' },
  { id: 'hydrating', label: 'Hydrating', kind: 'tag' as const, value: 'hydrating' },
];
