import { useState } from 'react';
import { Alert, Pressable, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { HapticPressable } from '@/components/HapticPressable';
import { Caption, Heading, Wordmark } from '@/components/ui';
import { Camera, MagnifyingGlass } from '@/components/icons';
import { colors, fonts, radii } from '@/constants/theme';
import { hapticSelect, hapticSuccess } from '@/lib/haptics';

export default function HomeScreen() {
  const router = useRouter(); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false);
  const go = () => { const q = query.trim(); if (!q) return; hapticSelect(); router.push({ pathname: '/results', params: { q } }); };
  const scan = async (camera: boolean) => { setBusy(true); try { const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert('Allow photos', 'Sourced needs access to identify the product in your photo.'); return; } const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.85 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.85 }); if (!result.canceled && result.assets[0]?.uri) { hapticSuccess(); router.push({ pathname: '/results', params: { imageUri: result.assets[0].uri } }); } } finally { setBusy(false); } };
  return <Screen><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 12 }}><Wordmark color={colors.bone} /><Text style={{ fontFamily: fonts.medium, color: colors.bone2 }}>Know before you buy.</Text></View><View style={{ flex: 1, justifyContent: 'center', paddingBottom: 24 }}><Heading size={48}>Someone's{ '\n' }already tried it.</Heading><Caption color={colors.bone2}>Real people. Real use. A clearer way to choose.</Caption><View style={{ marginTop: 28, backgroundColor: colors.lac, borderRadius: radii.search, padding: 8, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.line }}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={go} placeholder="Search a product or brand" placeholderTextColor={colors.bone3} style={{ flex: 1, height: 56, paddingHorizontal: 16, fontFamily: fonts.medium, fontSize: 16, color: colors.bone }} /><HapticPressable onPress={go} skipHaptic style={{ width: 52, height: 52, borderRadius: 18, backgroundColor: colors.hi, alignItems: 'center', justifyContent: 'center' }}><MagnifyingGlass size={22} color={colors.wine} weight="bold" /></HapticPressable></View><View style={{ flexDirection: 'row', gap: 10, marginTop: 12 }}><HapticPressable onPress={() => scan(true)} disabled={busy} style={{ flex: 1, borderRadius: 16, backgroundColor: colors.rosewoodSoft, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 9 }}><Camera size={20} color={colors.rosewood} weight="bold" /><Text style={{ fontFamily: fonts.semibold, color: colors.bone }}>{busy ? 'Opening…' : 'Scan with camera'}</Text></HapticPressable><HapticPressable onPress={() => scan(false)} style={{ flex: 1, borderRadius: 16, borderWidth: 1, borderColor: colors.line, padding: 16, alignItems: 'center', justifyContent: 'center' }}><Text style={{ fontFamily: fonts.semibold, color: colors.bone }}>Choose photo</Text></HapticPressable></View><Text style={{ marginTop: 18, fontFamily: fonts.regular, fontSize: 13, lineHeight: 19, color: colors.bone3 }}>Search by name or show us the packaging. Sourced will match it, then bring together owner stories, YouTube, Reddit and product facts.</Text></View></Screen>;
}
